In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [63]:
# du lieu huan luyen ngau nhien
xs = np.array([0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50, 
              2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50])
ys = np.array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])
df = pd.DataFrame({'hour': xs, 'pass': ys})
df

    hour  pass
0   0.50     0
1   0.75     0
2   1.00     0
3   1.25     0
4   1.50     0
5   1.75     0
6   1.75     1
7   2.00     0
8   2.25     1
9   2.50     0
10  2.75     1
11  3.00     0
12  3.25     1
13  3.50     0
14  4.00     1
15  4.25     1
16  4.50     1
17  4.75     1
18  5.00     1
19  5.50     1

In [64]:
def model_probability(w0, w1):
    def Compute(hour):
        return 1 / (1 + np.exp(-w0 - w1*hour))
    return Compute

def model_likelihood(w0, w1): # Niềm tin mô hình khớp như thế nào với dữ liệu, phải đầy đủ dữ liệu
    def Compute(hour, pass_):
        p = 1 / (1 + np.exp(-w0 - w1*hour))
        return np.where(pass_ == 1, p, 1-p)
        # if pass_ == 1: return p
        # else: return 1 - p
    return Compute

In [65]:
w0 = 1
w1 = 1
model1_probability = model_probability(w0, w1)
model1_likelihood = model_likelihood(w0, w1)
df['probability'] = model1_probability(df['hour'])
df['likelihood'] = model1_likelihood(df['hour'], df['pass'])
df

    hour  pass  probability  likelihood
0   0.50     0     0.817574    0.182426
1   0.75     0     0.851953    0.148047
2   1.00     0     0.880797    0.119203
3   1.25     0     0.904651    0.095349
4   1.50     0     0.924142    0.075858
5   1.75     0     0.939913    0.060087
6   1.75     1     0.939913    0.939913
7   2.00     0     0.952574    0.047426
8   2.25     1     0.962673    0.962673
9   2.50     0     0.970688    0.029312
10  2.75     1     0.977023    0.977023
11  3.00     0     0.982014    0.017986
12  3.25     1     0.985936    0.985936
13  3.50     0     0.989013    0.010987
14  4.00     1     0.993307    0.993307
15  4.25     1     0.994780    0.994780
16  4.50     1     0.995930    0.995930
17  4.75     1     0.996827    0.996827
18  5.00     1     0.997527    0.997527
19  5.50     1     0.998499    0.998499

Tính xác suất likelihood cho từng dữ liệu độc lập nhau. Vậy xác suất của một tập dữ liệu là tích của xác suất của từng dữ liệu độc lập nhau

Likelihood là độ đo xác suất của một dữ liệu độc lập nhau so với tập dữ liệu. Chúng ta phải tìm maximum likelihood để tìm ra phân phối xác suất phù hợp nhất cho tập dữ liệu.

In [66]:
likelihood1 = np.prod(df['likelihood'])
print(f'likelihood of model1 = {likelihood1}')
print(f'log-likelihood of model1 = {np.log(likelihood1)}')

likelihood of model1 = 3.2734361741132603e-13
log-likelihood of model1 = -28.747765957964315

In [67]:
w0 = 0
w1 = 0.8
model1_probability = model_probability(w0, w1)
model1_likelihood = model_likelihood(w0, w1)
df['probability'] = model1_probability(df['hour'])
df['likelihood'] = model1_likelihood(df['hour'], df['pass'])
df

    hour  pass  probability  likelihood
0   0.50     0     0.598688    0.401312
1   0.75     0     0.645656    0.354344
2   1.00     0     0.689974    0.310026
3   1.25     0     0.731059    0.268941
4   1.50     0     0.768525    0.231475
5   1.75     0     0.802184    0.197816
6   1.75     1     0.802184    0.802184
7   2.00     0     0.832018    0.167982
8   2.25     1     0.858149    0.858149
9   2.50     0     0.880797    0.119203
10  2.75     1     0.900250    0.900250
11  3.00     0     0.916827    0.083173
12  3.25     1     0.930862    0.930862
13  3.50     0     0.942676    0.057324
14  4.00     1     0.960834    0.960834
15  4.25     1     0.967705    0.967705
16  4.50     1     0.973403    0.973403
17  4.75     1     0.978119    0.978119
18  5.00     1     0.982014    0.982014
19  5.50     1     0.987872    0.987872

In [68]:
likelihood2 = np.prod(df['likelihood'])
print(f'likelihood of model2 = {likelihood2}')
print(f'log-likelihood of model2 = {np.log(likelihood2)}')

likelihood of model2 = 2.567875548455773e-08
log-likelihood of model2 = -17.477601821738332

Likelihood càng lớn thì xác suất của dữ liệu đó càng cao

Vậy mô hình 2 khớp hơn so với mô hình 1

Sau này cài đặt thì dùng minimize - log(likelihood)

In [70]:
threshold = 0.4
df['prediction'] = np.where(df['likelihood'] >= threshold, 1, 0)
df

    hour  pass  probability  likelihood  prediction
0   0.50     0     0.598688    0.401312           1
1   0.75     0     0.645656    0.354344           0
2   1.00     0     0.689974    0.310026           0
3   1.25     0     0.731059    0.268941           0
4   1.50     0     0.768525    0.231475           0
5   1.75     0     0.802184    0.197816           0
6   1.75     1     0.802184    0.802184           1
7   2.00     0     0.832018    0.167982           0
8   2.25     1     0.858149    0.858149           1
9   2.50     0     0.880797    0.119203           0
10  2.75     1     0.900250    0.900250           1
11  3.00     0     0.916827    0.083173           0
12  3.25     1     0.930862    0.930862           1
13  3.50     0     0.942676    0.057324           0
14  4.00     1     0.960834    0.960834           1
15  4.25     1     0.967705    0.967705           1
16  4.50     1     0.973403    0.973403           1
17  4.75     1     0.978119    0.978119           1
18  5.00     1     0.982014    0.982014           1
19  5.50     1     0.987872    0.987872           1